USE [master]
GO

CREATE DATABASE [BevasarloLista]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BevasarloLista', FILENAME = <path_to_.mdf_file> , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BevasarloLista_log', FILENAME = <path_to_log_file> , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BevasarloLista].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BevasarloLista] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BevasarloLista] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BevasarloLista] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BevasarloLista] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BevasarloLista] SET ARITHABORT OFF 
GO

ALTER DATABASE [BevasarloLista] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BevasarloLista] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BevasarloLista] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BevasarloLista] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BevasarloLista] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BevasarloLista] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BevasarloLista] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BevasarloLista] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BevasarloLista] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BevasarloLista] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BevasarloLista] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BevasarloLista] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BevasarloLista] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BevasarloLista] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BevasarloLista] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BevasarloLista] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BevasarloLista] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BevasarloLista] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BevasarloLista] SET  MULTI_USER 
GO

ALTER DATABASE [BevasarloLista] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BevasarloLista] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BevasarloLista] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BevasarloLista] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BevasarloLista] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BevasarloLista] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BevasarloLista] SET QUERY_STORE = ON
GO

ALTER DATABASE [BevasarloLista] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BevasarloLista] SET  READ_WRITE 
GO

